services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=host.docker.internal
    networks:
      - secure-auth-project
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => r.statusCode === 200 ? process.exit(0) : process.exit(1))"]
      interval: 30s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    environment:
      - BACKEND_URL=http://backend:3000
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - secure-auth-project
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost/health', (r) => r.statusCode === 200 ? process.exit(0) : process.exit(1))"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  secure-auth-project:
    driver: bridge
