apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: secure-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: sberston/backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: DB_HOST
          value: "host.docker.internal"  # Note: You might need to adjust this for k8s
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: SESSION_SECRET  
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: JWT_SECRET                
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: secure-auth
spec:
  selector:
    app: backend
  ports:
  - port: 3000
    targetPort: 3000